version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    env_file:
      - postgres.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9090:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:

networks:
  mynetwork:
    driver: bridge
