server:
  port: 8080

spring:
  application:
    name: CurrencyExchangeRatesProviderService

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/master.yaml

  scheduler:
    interval: 3600000

fixer:
  api:
    key: ${FIXER_API_KEY}
    url: https://data.fixer.io/api

exchangeratesapi:
  api:
    key: ${EXCHANGERATES_API_KEY}
    url: https://api.exchangeratesapi.io/v1/

