server:
  port: 8080

spring:
  ssl:
    bundle:
      pem:
        mybundle:
          truststore:
            certificate: classpath:keystore/cert.pem
  application:
    name: CurrencyExchangeRatesProviderService

  datasource:
    url: jdbc:postgresql://localhost:5432/databaseforcurrencies
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/master.yaml

  scheduler:
    interval: 3600000

fixer:
  api:
    key: 751c8d53f0ffb020e36053b7c5a36a2c
    url: http://data.fixer.io/api

openexchangerates:
  api:
    key: 2f1d3bbecd97433e8dbde4672f9b212f
    url: https://openexchangerates.org/api
