server:
  port: 8080

spring:
  application:
    name: CurrencyExchangeRatesProviderService

  datasource:
    url: jdbc:postgresql://localhost:5432/databaseforcurrencies
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/master.yaml

  scheduler:
    interval: 3600000

fixer:
  api:
    key: 71eb9f9d589f4b2c311dbda4dfac5bc3
    url: http://data.fixer.io/api
