server:
  port: 8080

spring:
  application:
    name: CurrencyExchangeRatesProviderService

  datasource:
    url: jdbc:postgresql://localhost:5432/databaseforcurrencies
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/master.yaml

  scheduler:
    interval: 120000

fixer:
  api:
    key: 7cd8abdf814040991ab6881311996ca4
    url: http://data.fixer.io/api/latest
