server:
  port: 8080

spring:
  ssl:
    bundle:
      pem:
        mybundle:
          truststore:
            certificate: classpath:keystore/cert.pem

  application:
    name: CurrencyExchangeRatesProviderService

  datasource:
    url: jdbc:postgresql://localhost:5432/databaseforcurrencies
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/master.yaml

  scheduler:
    interval: 3600000

fixer:
  api:
    key: a9fa92f463b10d67552fbb5282010a8f
    url: http://data.fixer.io/api

exchangeratesapi:
  api:
    key: 9b63e1b15b9b11829c399440e1a86ce8
    url: https://api.exchangeratesapi.io/v1/

