server:
  port: 8080

spring:
  application:
    name: CurrencyExchangeRatesProviderService

  datasource:
    url: jdbc:postgresql://localhost:5432/databaseforcurrencies
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
