server:
  port: 8080

spring:
  application:
    name: CurrencyExchangeRatesProviderService

  datasource:
    url: jdbc:postgresql://localhost:5432/databaseforcurrencies
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/master.yaml

  scheduler:
    interval: 3600000

fixer:
  api:
    key: e7b391d5110f607f29f117838c268207
    url: https://data.fixer.io/api

exchangeratesapi:
  api:
    key: 8c7e93adfbff98b7f69914f83dfdbd92
    url: https://api.exchangeratesapi.io/v1/

